Sprint1/step2
maxsergeev/react-burger pull request #2
Opened 2022-10-05 21:54 UTC by maxsergeev

2022-10-06 10:15 UTC, andryxxa93 requested changes
Проделана большая работа! Вы хорошо разобрались с функциональными компонентами, правильно используете useEffect и typescript.

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
1) Модалки не открываются при нажатии на ингредиент и кнопку заказ.
2) Необходимо добавить проверку успешности запроса.
3) Обратите внимание на ошибки в консоли (F12), их надо исправить - 
![Снимок экрана 2022-10-06 в 13 07 39](https://user-images.githubusercontent.com/60173362/194286404-d4507eb4-86eb-4aa7-9b82-47525ea6f2cb.png)
4. Поле ингредиента `__v` не имеет никакого отношения к счетчику ингредиента, поле `__v` это это версия документа в базе данных `mongo` и не должно никак использоваться в проекте.
5. Удалить ненужный файл с моковыми данными.

Более подробно описание проблемы смотрите комментарии в pull request.

Что понравилось:
1. Есть отписка от слушателей события.
2. Типизация через `typescript`.
3. Чистый и понятный код.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2022-10-06 10:15 UTC, andryxxa93 commented on src/components/ModalOverlay/ModalOverlay.tsx
> +            {children}
**Надо исправить**

у ModalOverlay не должно быть children, это просто компонент подложки а не контейнер

2022-10-06 10:15 UTC, andryxxa93 commented on src/components/App/App.tsx
> +            const res = await fetch(url);
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2022-10-06 10:15 UTC, andryxxa93 commented on src/components/App/App.tsx
> +            const d = await res.json();
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2022-10-06 10:15 UTC, andryxxa93 commented on src/components/App/App.tsx
> +        getData().catch(console.error);
**Можно улучшить**
Console.log нужен только для процесса разработки, перед сдачей проекта его нужно удалять, иначе она будет загружать консоль ненужной, а возможно и приватной информацией. А ошибку лучше записывать в state и показывать пользователю, чтобы он понимал, что происходит.

2022-10-06 10:15 UTC, andryxxa93 commented on src/components/App/App.tsx
> +        }
**Можно лучше**
Управление модалными окнами лучше вынести из App в компоненты конструктора и списка ингредиентов. В будущем `App` сильно увеличиться и станет неудобно его править.

2022-10-06 10:15 UTC, andryxxa93 commented on src/components/BurgerIngredients/IngredientItem/IngredientItem.tsx
> +                                <Counter  count={item?.__v} size={"default"}/>
**Необходимо исправить**
поле ингредиента `__v` не имеет никакого отношения к счетчику ингредиента, поле `__v` это это версия документа в базе данных `mongo` и не должно никак использоваться в проекте

2022-10-06 10:15 UTC, andryxxa93 commented on src/components/Modal/Modal.tsx
> +    }, [handleClose])
**Можно лучше**
Ваш вариант вполне рабочий, единственное - сложный. Можно просто передавать в `ModalOverlay` `onClick` функцию.

2022-10-06 10:15 UTC, andryxxa93 commented on src/utils/data.ts
> +export const data = [
**Необходимо исправить**
Этот файл больше не нужен, его необходимо удалить.

2022-10-06 21:42 UTC, maxsergeev commented on src/components/App/App.tsx
> +            const d = await res.json();
ok

2022-10-06 21:42 UTC, maxsergeev commented on src/components/App/App.tsx
> +        getData().catch(console.error);
ok

2022-10-06 21:45 UTC, maxsergeev commented on src/components/BurgerIngredients/IngredientItem/IngredientItem.tsx
> +                                <Counter  count={item?.__v} size={"default"}/>
убрал, прокинул как заглушку

2022-10-06 21:46 UTC, maxsergeev commented on src/utils/data.ts
> +export const data = [
ок

2022-10-06 21:46 UTC, maxsergeev commented on src/components/App/App.tsx
> +            const res = await fetch(url);
ok

2022-10-06 22:06 UTC, maxsergeev commented on src/components/App/App.tsx
> +        }
ok

2022-10-07 12:44 UTC, maxsergeev commented on src/components/ModalOverlay/ModalOverlay.tsx
> +            {children}
ok

2022-10-07 12:48 UTC, maxsergeev commented
Отчет по правкам:
**1. Модалки не открываются при нажатии на ингредиент и кнопку заказ.**
Данная функциональность была реализована и проверена перед пушем. Такой проблемы не увидел.

**2. Необходимо добавить проверку успешности запроса.**
Сделал

**3. Обратите внимание на ошибки в консоли (F12)**
Ошибки в консоли по key не было.  Все key прописаны до пуша.

**4. Поле ингредиента __v не имеет никакого отношения к счетчику ингредиента, поле __v это это версия документа в базе данных mongo и не должно никак использоваться в проекте.**
Убрал

**5. Удалить ненужный файл с моковыми данными.**
Удалил

2022-10-07 17:20 UTC, andryxxa93 approved these changes
Ваша работа принята! Удачного продолжения обучения!

2022-10-13 23:17 UTC, merged