[CB-10] update: роутинг + авторизация
maxsergeev/react-burger pull request #5
Opened 2022-10-31 23:25 UTC by maxsergeev

2022-11-01 16:49 UTC, randomroot requested changes
**Доброго времени суток!**

Вы проделали очень хорошую работу по внедрению роутинга в ваш проект, прекрасно поработали с тулкитом, с юмором подошли к экрану 404, так держать 👍 

Тем не менее, для успешной сдачи проекта, вам необходимо внимательно изучить комментарии, отмеченные в рамках ревью и внести изменения, обратив особое внимание на следующие моменты, выявленные в ходе проверки:

**Нужно исправить:**

- При прямом переходе на страницу профиля `/profile` происходит редирект на главную `/`
- На странице восстановления пароля следует убрать значение по-умолчанию, т.к. это вынуждает пользователя производить дополнительные действия по его очистке. В процессе отладки этот момент, действительно, полезен, но при релизе его лучше удалить;
- Согласно заданию, экран `/profile/orders` отображается пустым, поэтому сейчас не совсем очевидно, что осуществляется переход :)
- Кнопки "Отмена" и "Сохранить" следует показывать только, если пользователь отредактировал данные в форме и скрывать их после выполнения запроса или при нажатии кнопки "Отмена";
- После успешной авторизации должна происходить переадресация на тот маршрут, к которому пользователь не получил доступ ранее, например если сначала перейти по пути `/profile/orders`, а потом провести авторизацию, то пользователя перенаправит на экран конструктора, вместо истории заказов;
- Значение `main-send` из `localStorage` следует зачищать при выходе пользователя обратно на экран "входа", будем считать, что он отказался от восстановления. Иначе, получается, что страница остаётся доступной всё время;

**Можно улучшить:**

- Целесообразно добавить уведомления для пользователя в случае ошибки логина/регистрации/восстановления, т.к. при успехе они уже есть :)
- Формы лучше оборачивать в элемент `form` и использовать отправку по `onSubmit`, чтобы поддерживать семантику и увеличить удобство пользователей, например тогда появится возможность отправлять данные по нажатию `Enter`;

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**.

---

**Успешного вам рефакторинга и хорошего настроения!** 🐈

2022-11-01 16:49 UTC, randomroot commented on src/App.tsx
> +        history.replace('/');
🟡 **Можно улучшить:**

Лучше использовать `push`, т.к. `replace` перезаписывает историю браузера и удалит из неё переход на экран ингредиента.

2022-11-01 16:49 UTC, randomroot commented on src/App.tsx
> +            <div className={`${css.app}`}>
🟡 **Можно улучшить:**

В случае наличия только одной переменной использование шаблонных строк излишне

2022-11-01 16:49 UTC, randomroot commented on src/components/FormContainer/ForgotForm/ForgotForm.tsx
> +    const [value, setValue] = useState('bob@example.com')
🔴 **Нужно исправить:**

Следует убрать значение по-умолчанию, т.к. это вынуждает пользователя производить дополнительные действия по его очистке. В процессе отладки этот момент, действительно, полезен, но при релизе его лучше удалить;

2022-11-01 16:49 UTC, randomroot commented on src/components/FormContainer/LoginForm/LoginForm.tsx
> +    let handleLogin = useCallback((e: SyntheticEvent, value: IAuthData) => {
🟡 **Можно улучшить:**

Данное значение следует сделать константой, т.к. далее по коду оно не меняет своё значение :)

2022-11-01 16:49 UTC, randomroot commented on src/components/FormContainer/LoginForm/LoginForm.tsx
> +    const onChange = (e: any) => {
🔴 **Нужно исправить:**

Следует прописать правильную типизацию для параметра `e`, использование `any` не рекомендуется, т.к. по факту отключает все возможности TS по анализу правильности кода)

2022-11-01 16:49 UTC, randomroot commented on src/components/FormContainer/LoginForm/LoginForm.tsx
> +                history.replace("/");
🔴 **Нужно исправить:**

Следует перенаправлять пользователя на тот путь, с которого он попал на экран логина, за исключением случая, когда он пришёл сюда намеренно :)

2022-11-01 16:49 UTC, randomroot commented on src/components/FormContainer/LoginForm/LoginForm.tsx
> +            <EmailInput onChange={onChange} value={value.email} name={'email'} />
🟡 **Можно улучшить:**

Имеет смысл обернуть данные компоненты в форму, чтобы было верно семантически и логически, плюс пользователям удобно по нажатию `Enter` входить сразу, без нажатия на кнопку

2022-11-01 16:49 UTC, randomroot commented on src/components/FormContainer/LoginForm/LoginLinks.tsx
> +export const LoginLinks = () => {
🟡 **Можно улучшить:**

Разделение компонентов - это отличная практика, однако для небольших компонентов, состоящих из 1-2 HTML элементов это излишне, если они не переиспользуются в других местах, лучше перенести их непосредственно в компонент, который их использует

2022-11-01 16:49 UTC, randomroot commented on src/components/FormContainer/RegistryForm/RegistryForm.tsx
> +                alert('Пользователь зарегистрирован !');
🟢 **Отлично:**

Хорошо, что информируете пользователя 👍

2022-11-01 16:49 UTC, randomroot commented on src/components/FormContainer/ResetForm/ResetForm.tsx
> +    // console.log(isMailSend);
🟡 **Можно улучшить:**

Неиспользуемый код имеет смысл удалять из файлов, чтобы поддерживать чистоту кода. В случае необходимости его восстановления можно воспользоваться средствами Git-a.

2022-11-01 16:49 UTC, randomroot commented on src/components/FormContainer/ResetForm/ResetForm.tsx
> +        console.log(isMailSend)
🟡 **Можно улучшить:**

Логгирование очень полезно на этапе разработки, однако, при сдаче работы следует эти моменты удалить из кода, чтобы в консоли было минимальное количество информационных сообщений и легче было отлавливать ошибки после "выхода в релиз" :)

2022-11-01 16:49 UTC, randomroot commented on src/components/Header/HeaderMenuItem/HeaderMenuItem.tsx
> +const HeaderMenuItem = (props:IAppHeaderProps) =>  {
🟢 **Отлично:**

Правильно, что выделяете данный компонент в отдельный файл, чтобы избежать дублирования кода 👍

2022-11-01 16:49 UTC, randomroot commented on src/components/Header/HeaderMenuItem/HeaderMenuItem.tsx
> +    const { menuItemName, icon, active, link, exact = true } = props;
🟡 **Можно улучшить:** 

Декомпозицию можно перенести выше, непосредственно вместо параметра **props** `({...}: IAppHeaderProps) =>`

2022-11-01 16:49 UTC, randomroot commented on src/components/ProtectedRoute/ProtectedRoute.tsx
> +            exact={exact ? exact : false}
🟡 **Можно улучшить:**

Можно заменить на использование оператора ИЛИ: `exact || false`

2022-11-01 16:49 UTC, randomroot commented on src/pages/ForgotPass/ForgotPass.tsx
> +    if (cookie) {
🟡 **Можно улучшить:**

Здесь и для других страниц, на которые не должен попадать пользователь, если он авторизирован, не дублируйте в каждой странице эту логику, а создайте либо отдельный компонент `OnlyUnAuthRoute`, по аналогии c `ProtectedRoute`, который будет защищать эти страницы от авторизированных пользователей или доработайте компонент `ProtectedRoute`, передавая дополнительный параметр, определяющий в каком режиме работает компонент - только для авторизированных пользователей или только для неавторизированных пользователей, например

`const ProtectedRoute = ({ children, path, onlyUnAuth = false }) => {`

если установлен флаг `onlyUnAuth`  в пропсах - то значит переданный path доступен только неавторизированным пользователям, иначе он доступен только авторизированным пользователям

2022-11-01 16:49 UTC, randomroot commented on src/pages/NotFound404/NotFound404.tsx
> +            <p>Сорри иноземец, но такой страницы не существует :(</p>
🟢 **Отлично:**

Любой добрый юмор и цитаты отлично смотрятся в любом проекте, делая его живее :)

2022-11-01 16:49 UTC, randomroot commented on src/pages/Profile/Profile.tsx
> +                        В этом разделе вы можете изменить свои персональные данные
🟡 **Можно улучшить:**

Обратите внимание, что в дизайне в зависимости от страницы изменяется также и текст - в рамках следующего спринта данная тема может перейти в раздел обязательного исправления

2022-11-01 16:49 UTC, randomroot commented on src/services/slices/form/api/client.ts
> +            'Authorization': 'Bearer ' + `${getCookie('token')}`,
🟡 **Можно улучшить:**

Здесь и ниже шаблонную строку с заголовком авторизации имеет смысл расширить и на первое слово: ``` `Bearer ${getCookie('token')}` ```

2022-11-01 17:18 UTC, maxsergeev commented on src/App.tsx
> +        history.replace('/');
ok

2022-11-01 17:18 UTC, maxsergeev commented on src/App.tsx
> +            <div className={`${css.app}`}>
ok

2022-11-01 17:19 UTC, maxsergeev commented on src/components/FormContainer/ForgotForm/ForgotForm.tsx
> +    const [value, setValue] = useState('bob@example.com')
ok

2022-11-01 17:19 UTC, maxsergeev commented on src/components/FormContainer/LoginForm/LoginForm.tsx
> +    let handleLogin = useCallback((e: SyntheticEvent, value: IAuthData) => {
ok

2022-11-01 17:22 UTC, maxsergeev commented on src/components/FormContainer/LoginForm/LoginForm.tsx
> +    const onChange = (e: any) => {
ok

2022-11-01 17:24 UTC, maxsergeev commented on src/components/FormContainer/ResetForm/ResetForm.tsx
> +    // console.log(isMailSend);
ok

2022-11-01 17:24 UTC, maxsergeev commented on src/components/FormContainer/ResetForm/ResetForm.tsx
> +        console.log(isMailSend)
ok

2022-11-01 17:27 UTC, maxsergeev commented on src/components/Header/HeaderMenuItem/HeaderMenuItem.tsx
> +    const { menuItemName, icon, active, link, exact = true } = props;
ok

2022-11-01 17:28 UTC, maxsergeev commented on src/components/ProtectedRoute/ProtectedRoute.tsx
> +            exact={exact ? exact : false}
ok

2022-11-01 17:29 UTC, maxsergeev commented on src/pages/Profile/Profile.tsx
> +                        В этом разделе вы можете изменить свои персональные данные
ok

2022-11-01 17:30 UTC, maxsergeev commented on src/services/slices/form/api/client.ts
> +            'Authorization': 'Bearer ' + `${getCookie('token')}`,
ok

2022-11-01 21:43 UTC, maxsergeev commented on src/components/FormContainer/LoginForm/LoginForm.tsx
> +            <EmailInput onChange={onChange} value={value.email} name={'email'} />
ok

2022-11-01 21:44 UTC, maxsergeev commented on src/components/FormContainer/LoginForm/LoginForm.tsx
> +                history.replace("/");
ok

2022-11-02 07:33 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, критических замечаний больше не имеется, **отличная работа**, желаю вам хорошего дня и успехов в дальнейшем обучении! 🐈

2022-11-02 07:33 UTC, randomroot commented on src/pages/Profile/Profile.tsx
> +                            onChange={(e) => onChange(e)}
🟡 **Можно улучшить:**

Можно оставить просто `onChange={onChange}` без создания дополнительной стрелочной функции

2022-11-02 07:33 UTC, randomroot commented on src/pages/Profile/Profile.tsx
> +                        { hasChanged &&
🟡 **Можно улучшить:**

JSX элементы рекомендуется оборачивать в круглые скобки в рамках таких выражений, чтобы избегать возможных проблем с автоформатированием кода (см. https://medium.com/as-a-coder/why-you-should-wrap-your-jsx-with-parentheses-d7670293e45)

2022-11-14 21:15 UTC, merged